CREATE TABLE `boilerplate_module` (
    `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `TITLE` TEXT NOT NULL,
    `SORT` INT(11) DEFAULT 500,
    `CREATED` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(ID)
);